# Generated by Django 5.1.2 on 2024-10-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productavailability',
            name='unavailable_dates',
            field=models.JSONField(default=list),
        ),
    ]
